<div>
  <ul>
    <li>
      <a
        href="https://github.com/saitheninja/resume"
        target="_blank"
        rel="external"
      >
        GitHub
      </a>
    </li>
    <li>
      <a
        href="https://www.instagram.com/saitheninja/"
        target="_blank"
        rel="external"
      >
        Instagram
      </a>
    </li>
  </ul>
</div>
